---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-0d33de6c779f2cb71
  subnet_id: subnet-07d1f29dbba102c8e
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef tbagio Training Node for bagiotio-self"
    user: Administrator
    X-Contact: "Tio Bagio"
    X-Application: "apac"
    X-Dept: "sales"
    X-Customer: "apjcorp"
    X-Project: "BJC-Demo"
    X-Termination-Date: "2018-07-20T12:04:30Z"
    X-TTL: 4

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept
    local_mode: true
  attributes:
    chef_license: accept
    effortless:
      origin: chef
      pkg: chef-client
      channel: unstable

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-6
    transport:
      username: centos
      ssh_key:  ~\.ssh\id_rsa
    driver_config:
      user_data: ./kitchen_user_data

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
