
---
driver:
    security_group_ids: sg-0d33de6c779f2cb71
    subnet_id: subnet-07d1f29dbba102c8e
    tags:
    # Replace YOURNAME and YOURCOMPANY here
        Name: 'Chef training node for <YOURNAME>'
        user: Administrator
        X-Contact: 'Tio Bagio'
        X-Application: 'apac'
        X-Dept: 'sales'
        X-Customer: 'apjcorp'
        X-Project: 'Training'
        X-Termination-Date: '2018-07-20T12:04:30Z'
        X-TTL: 48

