---
driver:
  name: ec2
  aws_ssh_key_id: bagio-ireleand
  region: eu-west-1
  security_group_ids: sg-053b3b9a06121b8fa
  subnet_id: subnet-0f1e127abe5456236
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "<tbagio> Training Node"
    user: Administrator
    X-Contact: "Tio Bagio"
    X-Application: "apac"
    X-Dept: "sales"
    X-Customer: "apjcorp"
    X-Project: "Training"
    X-Termination-Date: "2018-07-20T12:04:30Z"
    X-TTL: 4

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept
    local_mode: true

verifier:
  name: inspec
  format: documentation

platforms:
  - name: ubuntu-1604
    transport:
      username: ubuntu
      ssh_key:  ~\.ssh\emea-sa-shared
    driver:
      image_search:
        owner-id: "099720109477"
        name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170414"
    driver_config:
      user_data: ./kitchen_user_data


suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
